name: projectm-tv

options:
  bundleIdPrefix: com.joshpointer
  deploymentTarget:
    tvOS: "26.0"

targets:
  projectm-tv:
    type: application
    platform: tvOS
    deploymentTarget: "26.0"
    sources:
      - projectm-tv
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: projectm-tv/Visualizer/ProjectMBridge.h
        HEADER_SEARCH_PATHS: $(SRCROOT)/Frameworks/libprojectM.xcframework/tvos-arm64/Headers
        OTHER_LDFLAGS: -lstdc++
        CLANG_ENABLE_MODULES: YES
        INFOPLIST_FILE: projectm-tv/Info.plist
        CODE_SIGN_ENTITLEMENTS: projectm-tv/projectm_tv.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.joshpointer.applejax
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: X6N4DF258V
        "CODE_SIGNING_ALLOWED[sdk=appletvsimulator*]": NO
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        SWIFT_VERSION: "5.0"
    dependencies:
      - framework: Frameworks/libprojectM.xcframework
        embed: false
      - sdk: OpenGLES.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: CoreVideo.framework
      - sdk: AVFoundation.framework
      - sdk: GameController.framework
      - sdk: CoreMedia.framework
      - sdk: UIKit.framework
      - sdk: MusicKit.framework
    scheme:
      build:
        targets:
          projectm-tv: all
      run:
        config: Debug
      test:
        config: Debug
